ifndef WGET
  ifneq ($(shell which wget),)
    WGET=wget -O
  endif
endif
ifndef WGET
  ifneq ($(shell which curl),)
    WGET=curl -o
  endif
endif
ifndef WGET
  $(error "wget or curl not found.")
endif
export WGET

ifndef PYROOT
  ifeq ($(shell python -c "import ROOT; print(1)" 2>/dev/null),1)
    PYROOT=1
  else
    $(warning PyROOT not installed. Data requiring PyROOT are not prepared.)
    PYROOT=0
  endif
endif
export PYROOT

ifneq ($(shell which WolframKernel),)
  WOLFRAM=WolframKernel
endif
ifndef WOLFRAM
  $(error "WolframKernel not found.")
else
  export WOLFRAM
endif
